### ISSUE TITLE
[Feature Request]: Custom background/background animations. 

### ISSUE THREAD

**Issue by DaBanana64** [stephini/SMAS_Launcher#20]
### Description

It would be cool to have custom backgrounds instead of a generic default blue color.

### Behavior

There would be a folder called `backgrounds` and you can put your custom backgrounds as `png` (or `gif` for animated ones) and on load, it they would appear.

### Examples

![image](https://github.com/stephini/SMAS_Launcher/assets/82652849/c9470ffd-367d-4f70-bfab-8e89c2c98041)
Something similar to this.

**Comment by stephini** [comment]
For the animation file, it is required to use a sprite sheet with dimensions of 987x525 per frame, arranged in a single column from top to bottom. Please note that this scale is subject to change only if additional features or new games necessitate modifications to the window size.

However, it is important to note that the successful implementation of the aforementioned requirements hinges upon resolving certain challenges. Specifically, the drop shadow feature currently lacks transparency, which could potentially conflict with both the proposed background animation and the intended background image. Overcoming this hurdle and finding a suitable solution will be imperative to ensure the seamless integration of these elements.
